CLASS zzcl_api_test DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_oo_adt_classrun .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zzcl_api_test IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main .

    CALL FUNCTION 'ZZFM_DEMO_OUT'.
  ENDMETHOD.
ENDCLASS.
